apiVersion: v1
data:
  secret_key_base: OGY2MDRiODgyMjQ3MGY5MzVlY2E4MmRmNjY2NmI0YjYyZWY0ZWY1ZGYyNDA1ZGYxMDE2MTVkOTMyN2YxZTI5M2JhMWE3OTNkYTk3MmM2OWRmMTVmM2I0N2FkMmU5NzU1ZjIzYjA4NDA0MWY3NDJhNzViZWFlOTI1Njk3NTA4OWQNCg==
  mysql_password: bXkgc2VjdXJlIHBhc3N3b3Jk
  mysql_user: cm9vdA==
kind: Secret
type: Opaque
metadata:
  name: app-secrets
