apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.16.111
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
